### ISSUE TITLE
Update ci.yml action

### ISSUE THREAD

**Issue by HamidMolareza** [HamidMolareza/github-action-typescript#14]
To evaluate various aspects, it's better to execute all steps to determine which stages succeeded or failed.  
For instance, a code might have a linting issue, but it’s good to know if that’s the only problem or if it also fails the tests.

Sample code that need to check:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        id: npm-ci
        run: npm ci
        continue-on-error: true

      - name: Check Format
        id: npm-format-check
        run: npm run format:check
        continue-on-error: true

      - name: Lint
        id: npm-lint
        run: npm run lint
        continue-on-error: true

      - name: Test
        id: npm-ci-test
        run: npm run ci-test
        continue-on-error: true

      - name: Final Check
        id: final-check
        run: |
          if [ "${{ steps.npm-ci.outcome }}" != "success" ] || \
             [ "${{ steps.npm-format-check.outcome }}" != "success" ] || \
             [ "${{ steps.npm-lint.outcome }}" != "success" ] || \
             [ "${{ steps.npm-ci-test.outcome }}" != "success" ]; then
            echo "One or more steps failed."
            exit 1
          fi

```
